In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = sns.load_dataset('tips')
print("Sample data:")
display(df.head())

print("\nData information:")
print(df.info())

print("\nDescriptive statistics:")
display(df.describe())

print("\nMissing values:")
print(df.isnull().sum())

Sample data:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Data information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB
None

Descriptive statistics:

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Missing values:
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
print("Sex values: ", df['sex'].unique()) # label encoding
print("\nSmoker values: ", df['smoker'].unique()) # label encoding
print("\nDay values: ", df['day'].unique()) # ordinal encoding -> mengurutkan hari berdasarkan rata-rata total bill
print("\nTime values: ", df['time'].unique()) # one-hot encoding

Sex values:  ['Female', 'Male']
Categories (2, object): ['Male', 'Female']

Smoker values:  ['No', 'Yes']
Categories (2, object): ['Yes', 'No']

Day values:  ['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

Time values:  ['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [11]:
# label encoding for 'sex' and 'smoker'
le = LabelEncoder()
df['sex_encoded'] = le.fit_transform(df['sex'])
df['smoker_encoded'] = le.fit_transform(df['smoker'])
display(df[['sex', 'sex_encoded', 'smoker', 'smoker_encoded']].sample(10))

        sex  sex_encoded smoker  smoker_encoded
174    Male            1    Yes               1
181    Male            1    Yes               1
156    Male            1     No               0
236    Male            1    Yes               1
146  Female            0     No               0
67   Female            0    Yes               1
183    Male            1    Yes               1
41     Male            1     No               0
97     Male            1    Yes               1
21   Female            0     No               0

In [18]:
# ordinal encoding for 'day'
avg_total_bill_per_day = df.groupby('day')['total_bill'].mean().sort_values()
day_order = avg_total_bill_per_day.index.tolist()
print(avg_total_bill_per_day)

ordinal_encoder = OrdinalEncoder(categories=[day_order])
df['day_encoded'] = ordinal_encoder.fit_transform(df[['day']])
display(df[['day', 'day_encoded']].sample(10))

day
Fri     17.151579
Thur    17.682742
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

C:\Users\asus\AppData\Local\Temp\ipykernel_9048\2861080938.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_total_bill_per_day = df.groupby('day')['total_bill'].mean().sort_values()

      day  day_encoded
63    Sat          2.0
161   Sun          3.0
233   Sat          2.0
157   Sun          3.0
137  Thur          1.0
121  Thur          1.0
12    Sun          3.0
185   Sun          3.0
209   Sat          2.0
35    Sat          2.0

In [20]:
# one-hot encoding for 'time'
time_one_hot = pd.get_dummies(df['time'], prefix='time')
df = df.join(time_one_hot)
display(df.head())

,total_bill,tip,sex,smoker,day,time,size,sex_encoded,smoker_encoded,day_encoded,time_Lunch,time_Dinner
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0,3.0,False,True
1,10.34,1.66,Male,No,Sun,Dinner,3,1,0,3.0,False,True
2,21.01,3.50,Male,No,Sun,Dinner,3,1,0,3.0,False,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1,0,3.0,False,True
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0,3.0,False,True

In [ ]:
display(df.query("smoker == 'Yes'").sample(10))